Shippinno\Job\Application\Job\StoredJob:
    exclusion_policy: NONE
    properties:
        id:
            type: integer
        name:
            type: string
        body:
            type: string
        createdAt:
            type: DateTimeImmutable
